When emulated user requests new access token, set emulator user id.
akalongman/laravel-lodash pull request #30
Opened 2024-09-03 11:32 UTC by Nika-Simonishvili

2024-09-03 15:32 UTC, akalongman requested changes

2024-09-03 15:32 UTC, akalongman commented on src/Lodash/Auth/Passport/Grants/InternalRefreshTokenGrant.php
> +use Laravel\Passport\TokenRepository;
აქ `Longman\LaravelLodash\Auth\Repositories\TokenRepository` ხომ არ უნდა გამოვიყენოთ?

2024-09-03 15:32 UTC, akalongman commented on src/Lodash/Auth/Passport/Grants/InternalRefreshTokenGrant.php
> +use Laravel\Passport\TokenRepository;
ან საერთოდ `Longman\LaravelLodash\Auth\Contracts\TokenRepositoryContract`

2024-09-03 15:32 UTC, akalongman commented on src/Lodash/Auth/Passport/Grants/InternalRefreshTokenGrant.php
> +use League\OAuth2\Server\Repositories\RefreshTokenRepositoryInterface;
აქაც ჩვენი არ უნდა იყოს? `Longman\LaravelLodash\Auth\Contracts\RefreshTokenRepositoryContract`

2024-09-04 07:34 UTC, Nika-Simonishvili commented on src/Lodash/Auth/Passport/Grants/InternalRefreshTokenGrant.php
> +use Laravel\Passport\TokenRepository;
done

2024-09-04 07:40 UTC, Nika-Simonishvili commented on src/Lodash/Auth/Passport/Grants/InternalRefreshTokenGrant.php
> +use League\OAuth2\Server\Repositories\RefreshTokenRepositoryInterface;
აქ მგონი არა, მაგ ჩვენ რეპოში baseRepo-დ აღწერილია `Laravel\Passport\RefreshTokenRepository` კლასი და `RefreshTokenGrant` (parent constructor-ის დაძახებისას)  ითხოვს `League\OAuth2\Server\Repositories\RefreshTokenRepositoryInterface` კლასს.

2024-09-04 09:43 UTC, akalongman requested changes

2024-09-04 09:43 UTC, akalongman commented on src/Lodash/Auth/Passport/Grants/InternalRefreshTokenGrant.php
> +use League\OAuth2\Server\Repositories\RefreshTokenRepositoryInterface;
@Nika-Simonishvili მაშინ ეს უნდა იყოს `RefreshTokenBridgeRepositoryContract` არა?

2024-09-04 10:57 UTC, Nika-Simonishvili commented on src/Lodash/Auth/Passport/Grants/InternalRefreshTokenGrant.php
> +use League\OAuth2\Server\Repositories\RefreshTokenRepositoryInterface;
done

2024-09-04 11:03 UTC, akalongman approved these changes

2024-09-04 11:03 UTC, merged